carbon/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include(('readings.urls', 'readings'), namespace='readings')),
]

readings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^upload/$', views.Upload.as_view(), name='upload'),
    url(r'^buildings/$', views.Buildings.as_view(), name='buildings'),
    url(r'^buildings/(?P<pk>\d+)/?$', views.BuildingDetail.as_view(), name='building_detail'),
]

readings/models.py
from django.db import models
from . import choices


class Building(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255)


class Meter(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    fuel = models.CharField(
        max_length=15,
        choices=choices.fuel
    )
    unit = models.CharField(
        max_length=5,
        choices=choices.units
    )

    building = models.ForeignKey('readings.Building', on_delete=models.CASCADE)


class MeterReading(models.Model):
    consumption = models.DecimalField(max_digits=10, decimal_places=5)
    reading_date_time = models.DateTimeField()

    meter = models.ForeignKey('readings.Meter', on_delete=models.CASCADE)

readings/forms.py
from django import forms
import csv
import codecs

from . import choices, mappings


class Upload(forms.Form):
    data_file = forms.FileField()
    data_type = forms.ChoiceField(choices=choices.data_types)

    def clean_data_file(self):
        data_type = self.data['data_type']
        f = self.cleaned_data['data_file']
        mapping = getattr(mappings, data_type)

        reader = csv.DictReader(codecs.iterdecode(f, 'utf-8-sig'), delimiter=',')

        actual_cols = list(filter(lambda field: field, reader.fieldnames))
        if not all(col in actual_cols for col in mapping.fields):
            raise forms.ValidationError(
                f"The CSV '{f.name}' does not have the correct format for type '{data_type}'"
            )

        return f

readings/views.py
import json

from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.db.models import Sum, Q
from django.db.models.functions import TruncDay
from django.core.serializers.json import DjangoJSONEncoder

from . import forms, models
from .data import store_data


class Upload(FormView):
    template_name = 'upload.html'
    form_class = forms.Upload
    success_url = '/upload/'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            store_data(request.POST['data_type'], request.FILES['data_file'])
            return self.form_invalid(form)
        else:
            return self.form_invalid(form)


class Buildings(ListView):
    model = models.Building
    template_name = 'buildings.html'


class BuildingDetail(DetailView):
    model = models.Building
    template_name = 'meters.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        meters = models.Meter.objects.filter(building_id=context['building'].id)
        context['meters'] = meters

        meter_ids = [m.id for m in meters]
        daily_consumption = (
            models.MeterReading.objects
                .filter(meter_id__in=meter_ids)
                .annotate(day=TruncDay('reading_date_time'))
                .values('day')
                .annotate(
                    total_water=Sum('consumption', filter=Q(meter__fuel='Water')),
                    total_gas=Sum('consumption', filter=Q(meter__fuel='Natural Gas')),
                    total_electricity=Sum('consumption', filter=Q(meter__fuel='Electricity'))
                )
        )
        context['daily_consumption'] = json.dumps(list(daily_consumption), cls=DjangoJSONEncoder)

        return context

readings/templates/buildings.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Buildings</title>
</head>

<body>
  <h1>Buildings</h1>
  {% if object_list %}
  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
    {% for building in object_list %}
    <tr>
      <td>{{ building.id }}</td>
      <td><a href="{% url 'readings:building_detail' building.id %}">{{ building.name }}</a></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>No buildings yet.</p>
  {% endif %}
</body>
</html>

readings/templates/meters.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Meters</title>

  <style>
    #chart {
      width: 960px;
      height: 500px;
      border: 1px solid #000000;
    }

    .gas {
      fill: none;
      stroke: rgb(180, 99, 70);
      stroke-width: 2px;
    }

    .electricity {
      fill: none;
      stroke: rgb(79, 180, 70);
      stroke-width: 2px;
    }
  </style>

  {% if meters %}
  <script src="https://d3js.org/d3.v4.js"></script>
  <script>
    {% autoescape off %}
    var consumption_data =  {{ daily_consumption }};
    {% endautoescape %}

    window.onload = function() {
      // set the dimensions and margins of the graph
      var margin = {top: 20, right: 20, bottom: 30, left: 50},
          width = 960 - margin.left - margin.right,
          height = 500 - margin.top - margin.bottom;

      // parse the date / time
      var parseTime = d3.timeParse("%Y-%m-%dT%H:%M:%SZ");

      // set the ranges
      var x = d3.scaleTime().range([0, width]);
      var y = d3.scaleLinear().range([height, 0]);

      // define the lines
      var gasChart = d3.line()
          .x(function(d) { return x(d.date); })
          .y(function(d) { return y(d.total_gas); });

      var electricityChart = d3.line()
          .x(function(d) { return x(d.date); })
          .y(function(d) { return y(d.total_electricity); });

      var svg = d3.select("#chart").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform",
              "translate(" + margin.left + "," + margin.top + ")");

      consumption_data.forEach(function(d) {
        d.date = parseTime(d.day);
        d.total_electricity = d.total_electricity ? parseFloat(d.total_electricity) : 0;
        d.total_gas = d.total_gas ? parseFloat(d.total_gas) : 0;
      });

      // Scale the range of the data
      x.domain(d3.extent(consumption_data, function(d) { return d.date; }));
      y.domain([0, d3.max(consumption_data, function(d) { return d3.max([d.total_gas, d.total_electricity]); })]);

      // Add the valueline path.
      svg.append("path")
          .data([consumption_data])
          .attr("class", "gas")
          .attr("d", gasChart);

      svg.append("path")
          .data([consumption_data])
          .attr("class", "electricity")
          .attr("d", electricityChart);

      // Add the X Axis
      svg.append("g")
          .attr("transform", "translate(0," + height + ")")
          .call(d3.axisBottom(x));

      // Add the Y Axis
      svg.append("g")
          .call(d3.axisLeft(y));
    }
  </script>
  {% endif %}
</head>

<body>
  <h1>Meters for building {{ object.name }}</h1>
  {% if meters %}
  <table>
    <tr>
      <th>ID</th>
      <th>Fuel</th>
      <th>Unit</th>
    </tr>
    {% for meter in meters %}
    <tr>
      <td>{{ meter.id }}</td>
      <td>{{ meter.fuel }}</td>
      <td>{{ meter.unit }}</td>
    </tr>
    {% endfor %}
  </table>

  <h2>Consumption</h2>
  <p>Red - Natural Gas, Green - Electricity</p>
  <div id="chart"></div>

  {% else %}
  <p>No meters in this building yet.</p>
  {% endif %}


</body>

readings/templates/upload.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Upload data</title>
</head>

<body>
  <h1>Upload data</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
</body>
</html>